name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Convert deb to IPA
        run: |
          curl -L -o app.deb "${{ github.event.inputs.deb }}"
          
          dpkg-deb -X app.deb app

          mkdir -p ipa/Payload

          cp -R app/Applications/* ipa/Payload/

          cd ipa
          zip -r ../Kodi.ipa .

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Kodi.ipa
          path: Kodi.ipa
          compression-level: 0
